// Currency symbol mapping
export const getCurrencySymbol = (currency: string): string => {
    const symbols: Record<string, string> = {
        USD: '$',
        EUR: '€',
        GBP: '£',
        JPY: '¥',
        CNY: '¥',
        INR: '₹',
        AUD: 'A$',
        CAD: 'C$',
        CHF: 'Fr',
        SEK: 'kr',
        NZD: 'NZ$',
        KRW: '₩',
        SGD: 'S$',
        HKD: 'HK$',
        NOK: 'kr',
        MXN: '$',
        ZAR: 'R',
        BRL: 'R$',
        RUB: '₽',
        TRY: '₺',
        PLN: 'zł',
        THB: '฿',
        IDR: 'Rp',
        MYR: 'RM',
        PHP: '₱',
        DKK: 'kr',
        CZK: 'Kč',
        HUF: 'Ft',
        RON: 'lei',
        ILS: '₪',
        CLP: '$',
        ARS: '$',
        COP: '$',
        EGP: 'E£',
        SAR: 'SR',
        AED: 'د.إ',
        QAR: 'QR',
        KWD: 'KD',
        BHD: 'BD',
        OMR: 'OMR',
        JOD: 'JD',
        LBP: 'L£',
        PKR: '₨',
        BDT: '৳',
        LKR: 'Rs',
        NPR: 'Rs',
        VND: '₫',
        UAH: '₴',
        BGN: 'лв',
        HRK: 'kn',
        ISK: 'kr',
        MAD: 'DH',
        TND: 'DT',
        KES: 'KSh',
        NGN: '₦',
        GHS: 'GH₵',
        UGX: 'USh',
        TZS: 'TSh',
        ETB: 'Br',
        XOF: 'CFA',
        XAF: 'FCFA',
    };

    return symbols[currency.toUpperCase()] || currency.toUpperCase();
};

// Format currency with symbol
export const formatCurrency = (amount: number, currency: string): string => {
    const symbol = getCurrencySymbol(currency);
    return `${symbol}${amount.toFixed(2)}`;
};
